# Generated by Django 5.0.7 on 2024-08-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0004_adminlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPassWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='adminlogin',
            name='password',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='adminlogin',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
