# Generated by Django 5.0.7 on 2024-08-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0005_userpassword_alter_adminlogin_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='category_images/')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AlterField(
            model_name='userpassword',
            name='password',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userpassword',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
