# Generated by Django 5.0.7 on 2024-08-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0006_category_delete_person_alter_userpassword_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('u_first_name', models.CharField(max_length=50)),
                ('u_last_name', models.CharField(max_length=50)),
                ('u_email', models.EmailField(max_length=254, unique=True)),
                ('u_phone_number', models.CharField(max_length=10, unique=True)),
                ('u_street_address', models.CharField(max_length=100)),
                ('u_state', models.CharField(max_length=50)),
                ('u_country', models.CharField(max_length=50)),
                ('u_pin_code', models.CharField(max_length=6)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
