# Generated by Django 5.0.7 on 2024-08-12 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0007_customer_info_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminLogin',
        ),
    ]
