# Generated by Django 5.0.7 on 2024-08-12 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0009_adminlogin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminLogin',
        ),
    ]
