# Generated by Django 5.0.7 on 2024-08-15 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0011_adminlogin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPassWord',
        ),
    ]
