# Generated by Django 5.0.7 on 2024-09-17 07:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0013_customerinfo_delete_customer_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='u_country',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='u_email',
            field=models.EmailField(editable=False, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='u_name',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='u_password',
            field=models.CharField(editable=False, max_length=128, validators=[django.core.validators.MinLengthValidator(8, message='Password must be at least 8 characters long.')]),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='u_phone_number',
            field=models.CharField(editable=False, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='u_pin_code',
            field=models.CharField(editable=False, max_length=6, validators=[django.core.validators.RegexValidator(message='Pin code must be 6 digits.', regex='^\\d{6}$')]),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='u_state',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='u_street_address',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
