# Generated by Django 5.0.7 on 2024-09-18 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0018_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
