# Generated by Django 5.0.7 on 2024-09-18 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0022_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_id',
            new_name='id',
        ),
    ]
