# Generated by Django 5.0.7 on 2024-09-18 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0023_rename_product_id_product_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
