# Generated by Django 5.0.7 on 2024-09-20 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0026_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
