# Generated by Django 5.0.7 on 2024-09-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0027_delete_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email_id', models.EmailField(max_length=255)),
                ('product_id', models.CharField(editable=False, max_length=10)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
    ]
