# Generated by Django 5.0.7 on 2024-10-01 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0028_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerinfo',
            old_name='u_country',
            new_name='u_city',
        ),
    ]
