# Generated by Django 5.0.7 on 2024-10-01 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0030_delete_customerinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=50)),
                ('email', models.EmailField(editable=False, max_length=50, unique=True)),
                ('phonenumber', models.CharField(editable=False, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits.', regex='^\\d{10}$')])),
                ('streetaddress', models.CharField(editable=False, max_length=100)),
                ('state', models.CharField(editable=False, max_length=50)),
                ('city', models.CharField(editable=False, max_length=50)),
                ('pincode', models.CharField(editable=False, max_length=6, validators=[django.core.validators.RegexValidator(message='Pin code must be 6 digits.', regex='^\\d{6}$')])),
                ('password', models.CharField(editable=False, max_length=8, validators=[django.core.validators.MinLengthValidator(8, message='Password must be at least 8 characters long.')])),
            ],
        ),
    ]
