# Generated by Django 5.0.7 on 2024-10-01 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0032_alter_customerinfo_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminLogin',
        ),
    ]
