# Generated by Django 5.0.7 on 2024-10-01 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0033_delete_adminlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(editable=False, max_length=50, unique=True)),
                ('phonenumber', models.CharField(editable=False, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits.', regex='^\\d{10}$')])),
                ('password', models.CharField(max_length=8)),
            ],
        ),
    ]
