# Generated by Django 5.0.7 on 2024-10-01 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0034_admininfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
