# Generated by Django 5.0.7 on 2024-10-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0041_rename_category_id_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=60),
        ),
    ]
