# Generated by Django 5.0.7 on 2024-10-01 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0042_alter_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
