# Generated by Django 5.0.7 on 2024-10-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0046_alter_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=5),
        ),
    ]
