# Generated by Django 5.0.7 on 2024-10-01 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0048_alter_cart_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
