# Generated by Django 5.0.7 on 2024-10-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0052_rename_contact_contact_phonenumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('o_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('product', models.JSONField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=10)),
                ('payment_mode', models.CharField(max_length=50)),
                ('payment_status', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
