# Generated by Django 5.1.2 on 2024-10-22 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0054_alter_orderinfo_o_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillInfo',
            fields=[
                ('b_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('u_id', models.CharField(max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('o_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommers.orderinfo')),
            ],
        ),
    ]
