# Generated by Django 5.1.2 on 2024-10-22 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0055_billinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillInfo',
        ),
    ]
