# Generated by Django 5.1.2 on 2024-10-26 11:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0057_rename_u_email_cart_email_remove_cart_id_cart_c_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderInfo',
        ),
        migrations.AlterField(
            model_name='admininfo',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='admininfo',
            name='phonenumber',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits.', regex='^\\d{10}$')]),
        ),
    ]
