# Generated by Django 5.1.2 on 2024-10-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0058_delete_orderinfo_alter_admininfo_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('o_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=20)),
                ('product', models.JSONField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=10)),
                ('payment_mode', models.CharField(max_length=50)),
                ('payment_status', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
